server:
  port: ${port:8012}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aztec1234/configs
          skip-ssl-validation: true
  application:
    name: config-server
  devtools:
    restart:
      enabled: true
#http://localhost:8012/actuator/configprops
eureka:
  password: admin
  instance:
    secure-port-enabled: true
    hostname: localhost
    status-page-url: http://localhost:${server.port}/actuator/info
    home-page-url: http://localhost:${server.port}
    secure-port: ${server.port}
    health-check-url: http://localhost:${server.port}/actuator/health
    non-secure-port-enabled: false
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka